V2 filters backend
TritonSE/USHS-Housing-Portal pull request #101
Opened 2024-05-22 00:31 UTC by RamtinTJB

## Tracking Info

Resolves #100 

## Changes

- Added new fields for the new filters in the frontend and backend
- Integrated the v2 filters in the backend API
- Refactored frontend code
- Added FiltersConext

## Testing

Manually verified the different combination of filters to make sure they display the right results

**Note**: I haven't figured out a way to implement the multi-option (checkbox) yet I'll add that pretty soon.

## Confirmation of Change

![image](https://github.com/TritonSE/USHS-Housing-Portal/assets/69605985/9b3c4830-5849-46d0-a2e1-da78c00ce7da)

2024-05-22 01:23 UTC, petabite commented on backend/src/services/units.ts
> +
Can we remove this?

2024-05-22 01:47 UTC, petabite requested changes
Looking great 🔥 💯   Left a couple comments below.

Also, do you think it's possible to implement the "$" and "sqft" prefix/postfix as in the designs?

<img width="164" alt="image" src="https://github.com/TritonSE/USHS-Housing-Portal/assets/24444266/79a7f859-6617-47d5-b50d-32f93b520e6c">

2024-05-22 01:47 UTC, petabite commented on backend/src/services/units.ts
> +
Are these filters not working?

2024-05-22 01:47 UTC, petabite commented on frontend/src/api/units.ts
> +    console.log(url);
```suggestion
```

2024-05-22 01:47 UTC, petabite commented on frontend/src/components/FilterPanel.tsx
> +      search: filters.search ?? "0",
```suggestion
      search: filters.search ?? "",
```

There seems to be a bug where clicking "Apply" sets the search value to "0"

2024-05-22 01:47 UTC, petabite commented on frontend/src/components/MinMaxFilter.tsx
> +export const MinMaxFilter = (props: MinMaxFilterProps) => {
lol nice

2024-05-22 01:47 UTC, petabite commented on frontend/src/pages/Home.tsx
> +    <FiltersContext.Provider value={{ filters, setFilters }}>
It also looks like the filter context stuff might be broken. When I click "Back" from the Unit Details page, the filter criteria get reset to their default values.

2024-05-22 03:52 UTC, petabite commented on frontend/src/pages/Home.tsx
> +    <FiltersContext.Provider value={{ filters, setFilters }}>
Ah, I did some digging and it looks like the `FilterContext.Provider` got removed in [this commit](https://github.com/TritonSE/USHS-Housing-Portal/commit/02ad2f7d90b5c11bef3d7b5bbc894b013d204660#diff-9f4fbb52c544c388744cd765e62f81f3049a5d32948140308a6a623ee4a01005).

2024-05-30 07:27 UTC, petabite reviewed
This looks awesome! I just added some code to support persisting the filters when the user clicks "Back" on the unit details page. Should be good to go once you add the "Any" option for the "Housing Authority" filter!

2024-06-01 01:20 UTC, petabite approved these changes
🚢 !!

2024-06-03 23:23 UTC, soma-p approved these changes
PR looks great!

2024-06-04 02:35 UTC, merged