Karen/unit list view
TritonSE/USHS-Housing-Portal pull request #102
Opened 2024-05-22 20:05 UTC by PoliteUnicorn

## Tracking Info

Resolves #93

## Changes
Implemented the card/list view toggle button at the top of the page and the list view for units.
Also replaced paginator with V2 button version. 

## Testing
Tested by switching between unit and list views and trying the paginator on varying numbers of pages. 

## Confirmation of Change
The implemented list view: 
<img width="1427" alt="Screenshot 2024-05-22 at 1 03 12 PM" src="https://github.com/TritonSE/USHS-Housing-Portal/assets/35088854/b3dd9ec8-a4e6-4712-acaf-295cd2e70e78">
<img width="1427" alt="Screenshot 2024-05-22 at 1 03 19 PM" src="https://github.com/TritonSE/USHS-Housing-Portal/assets/35088854/b6a640b8-cb9a-4fb5-8d8a-484978dc3f27">

**The paginator:** 
<img width="348" alt="Screenshot 2024-05-22 at 1 03 42 PM" src="https://github.com/TritonSE/USHS-Housing-Portal/assets/35088854/f6e1359f-3bb2-4301-84e0-6d9467972047">
<img width="1032" alt="Screenshot 2024-05-22 at 1 03 54 PM" src="https://github.com/TritonSE/USHS-Housing-Portal/assets/35088854/33e142a8-7296-4a5b-83a4-7d2622413ff9">
<img width="1056" alt="Screenshot 2024-05-22 at 1 04 00 PM" src="https://github.com/TritonSE/USHS-Housing-Portal/assets/35088854/f338a6e6-a56a-4fa0-aa03-70526089efe3">
<img width="1063" alt="Screenshot 2024-05-22 at 1 04 06 PM" src="https://github.com/TritonSE/USHS-Housing-Portal/assets/35088854/6cdfcb4c-edbf-46e2-9b21-86300807c774">

2024-05-23 05:06 UTC, petabite requested changes
This looks awesome! Left some small comments below. Also, do you think it is possible to vertically center the content in each list item?

![image](https://github.com/TritonSE/USHS-Housing-Portal/assets/24444266/2dde0b09-5b55-43ed-ae87-99d15a35a066)

2024-05-23 05:06 UTC, petabite commented on frontend/public/Group.svg
Looks like this file isn't used anywhere

2024-05-23 05:06 UTC, petabite commented on frontend/src/components/ReferralTable.tsx
> +// import { Pagination } from "./Pagination";
```suggestion
```
Can we remove this?

2024-05-23 05:06 UTC, petabite commented on frontend/src/components/Table.tsx
> +            <Pagination
Thanks for porting over the new pagination here!

2024-05-29 22:08 UTC, PoliteUnicorn commented on frontend/public/Group.svg
Deleted!

2024-05-29 22:11 UTC, PoliteUnicorn reviewed
Fixed changes!

2024-05-30 04:23 UTC, petabite requested changes
It looks like the row content isn't vertically centered yet.

Also, do you think you can fix the spacing of the "No matching units found" text here?

<img width="1057" alt="image" src="https://github.com/TritonSE/USHS-Housing-Portal/assets/24444266/353f0d1a-37c5-478a-b2a5-5410030cd387">

2024-06-03 23:28 UTC, PoliteUnicorn commented
Fixed alignment issues and text.

2024-06-04 02:34 UTC, petabite approved these changes
Nice work!! 🚢

2024-06-04 02:37 UTC, RamtinTJB approved these changes
Great work! 💯 🗿

2024-06-04 04:16 UTC, merged