Edit Renter Candidate Page
TritonSE/USHS-Housing-Portal pull request #104
Opened 2024-05-24 05:32 UTC by Azhou2023

## Tracking Info

Resolves #103 

## Changes

Added the edit renter candidate process flow after pressing the "Edit" button. Allows changes to be made to all renter candidate info fields as well as to their current referrals. Implemented deletion for referrals. 

Also implemented a max number of 10 photos and 2 videos per unit, as well as a 200MB size cap for uploaded videos.

## Testing

Tested every edit field thoroughly, checked that deletion worked in backend and reflected in frontend. Checked for photo/video uploading that uploading capped with correct criteria (in both normal uploading and uploading at unit creation).

## Confirmation of Change

<img width="1512" alt="Screenshot 2024-05-23 at 10 29 24 PM" src="https://github.com/TritonSE/USHS-Housing-Portal/assets/57163201/780979d4-280c-4c97-9caa-5beaf4f81236">
<img width="1399" alt="Screenshot 2024-05-23 at 10 29 36 PM" src="https://github.com/TritonSE/USHS-Housing-Portal/assets/57163201/2e980f5a-9888-46da-968e-ff993937f0a1">
<img width="1512" alt="Screenshot 2024-05-23 at 10 29 43 PM" src="https://github.com/TritonSE/USHS-Housing-Portal/assets/57163201/5fc5515f-c63e-44dd-a36e-f604072146df">
<img width="1511" alt="Screenshot 2024-05-23 at 10 29 52 PM" src="https://github.com/TritonSE/USHS-Housing-Portal/assets/57163201/14439e75-2e9e-4ecc-9010-b6f2de8762cc">
<img width="963" alt="Screenshot 2024-05-23 at 10 31 22 PM" src="https://github.com/TritonSE/USHS-Housing-Portal/assets/57163201/66841e4f-0885-4d7d-bf4b-d281cd7c0c06">

2024-05-29 22:01 UTC, PoliteUnicorn approved these changes
This looks good to me!

2024-05-30 08:54 UTC, petabite requested changes
Nice work! 💯 Left some tiny comments below, but should be good to go once you add the fixes we discussed in the team meeting!

2024-05-30 08:54 UTC, petabite commented on frontend/src/components/ListingForm/ImagesVideos.tsx
> +        console.log(data);
```suggestion
```

2024-05-30 08:54 UTC, petabite commented on frontend/src/pages/RenterCandidatePage.tsx
> +              Back to Listing
Users will be able to access the Renter Candidate page from the All Renter Candidate page (once it's implemented) as well. Thoughts on calling this "Back" to keep it more general?
```suggestion
              Back 
```

2024-06-01 01:30 UTC, petabite approved these changes
Good stuff 🔥

2024-06-03 21:58 UTC, merged