Profile Page
TritonSE/USHS-Housing-Portal pull request #47
Opened 2024-02-22 00:06 UTC by Azhou2023

## Tracking Info

Resolves #42 

## Changes

Added Profile Page with additional elevation permissions for Housing Locators.

## Testing

Tested that backend routes did elevate users, tested select component rigourously, tested that housing locator accounts has different views and permissions as non-HL accounts.

## Confirmation of Change

**Make sure to elevate yourself in the staging DB to see the housing locator view**

![Screenshot_2](https://github.com/TritonSE/USHS-Housing-Portal/assets/57163201/f9229b16-d5ce-44b9-96a5-2af715ff5b3a)
![Screenshot_8](https://github.com/TritonSE/USHS-Housing-Portal/assets/57163201/57166282-6b32-4e10-ba5f-e594d272e7ec)
![Screenshot_10](https://github.com/TritonSE/USHS-Housing-Portal/assets/57163201/a37fa0e2-a316-4637-acde-de1a75d6c16f)
![Screenshot_11](https://github.com/TritonSE/USHS-Housing-Portal/assets/57163201/c04fecc2-460a-4e6e-b9ea-20dba623c4f5)

2024-02-23 08:05 UTC, petabite requested changes
This works like a charm! 💯  I demoed this to the clients today and they were happy with it!

2024-02-23 08:05 UTC, petabite commented on frontend/src/contexts/DataContext.tsx
> +  const [allReferringStaff, setALlReferringStaff] = useState<User[]>([]);
```suggestion
  const [allReferringStaff, setAllReferringStaff] = useState<User[]>([]);
```
small typo

2024-02-23 08:05 UTC, petabite commented on frontend/src/contexts/DataContext.tsx
> +      setALlReferringStaff(data.filter((user: User) => !user.isHousingLocator));
```suggestion
      setAllReferringStaff(data.filter((user: User) => !user.isHousingLocator));
```

2024-02-23 08:05 UTC, petabite commented on frontend/src/pages/Profile.tsx
> +            setCurrentRS(undefined);
Totally up to you: It might simplify things if `DataContext` provides a refetch function that you can call to refetch all the users after the user gets elevated ([example](https://github.com/TritonSE/TAP-Foster-Dog-Matching/blob/101fb04c11dd45d90e6956a7c417414006bbafe4/client/src/contexts/DataContext.js#L49)). That way all the state will just naturally update with the `useEffect` you have below.

2024-02-23 08:05 UTC, petabite commented on frontend/src/components/UserDropdown.tsx
> +    }
Might be able to do this functionally using [`filter`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter)

2024-02-24 20:24 UTC, petabite approved these changes
LGTM 🚢  Nice work!

2024-02-29 00:20 UTC, soma-p approved these changes
I think it all looks good! I looked through all of the different requirements for the PR and it all seems to check out.

2024-02-29 00:24 UTC, merged