Referral Table: UI, GET Route, Schema
TritonSE/USHS-Housing-Portal pull request #54
Opened 2024-03-03 19:10 UTC by JamesZhang878

## Tracking Info

Resolves #36 

## Changes
Backend:
- Referral Mongoose Schema
- GET route for referrals

Frontend:
- GET API route for referrals
- Referral Table UI. (Only gets and displays referral info. Edits aren't supported yet)

## Testing
Backend:
- Searched up http://localhost:5173/unit/65cd898003b744c6d21dd423 with and without my account set as housingLocator. 
> Result: When I was a housingLocator, I can see all of the referrals. When I'm not a housing locator, I just see None.
- Searched up different units where some units had referrals and others didn't. Same result as previous test.

Frontend:
- Ran the app locally and tested component functionality. See demo below

## Confirmation of Change
Uploading ReferralTableDemo-720.mov…

2024-03-05 08:22 UTC, petabite requested changes
Nice work! This is looking fire! Also, thanks for the video demo, that was super helpful. I left some comments below. It also looks like there is a merge conflict and frontend lint issues to fix.

2024-03-05 08:22 UTC, petabite commented on frontend/src/components/ReferralTable.tsx
> +        <ReferralTableTitle>Referrals:</ReferralTableTitle>
The font for this looks a little off just looking at the demo video

2024-03-05 08:22 UTC, petabite commented on backend/src/services/referral.ts
> +  const referrals = await ReferralModel.find({ unitId: id }).populate("renterCandidate");
Do you think we can populate the assigned housing locator and referring staff as well? I think that information would be helpful later on.

2024-03-05 08:22 UTC, petabite commented on backend/src/models/referral.ts
> +    assignedReferringStaffId: {
```suggestion
    assignedHousingLocator: {
      type: Schema.Types.ObjectId,
      required: false,
    },
    // Should be set to the user that created the referral (RS or HL)
    assignedReferringStaff: {
```

As per previous suggestion

2024-03-05 08:22 UTC, petabite commented on frontend/src/api/units.ts
> +};
`RenterCandidate` should have a couple more fields. See [schema](https://docs.google.com/document/d/1ef1bwMTZANkUs5uyz-D93v85jv7CfmoDGwE5ANlX_BE/edit#bookmark=id.77oihdu4yyj0)

2024-03-05 08:22 UTC, petabite commented on frontend/src/api/units.ts
> +  assignedReferringStaffId: string;
```suggestion
  assignedHousingLocator: string;
  assignedReferringStaff: string;
```

2024-03-05 08:22 UTC, petabite commented on frontend/src/components/ReferralTablePagination.tsx
> +      <CurrPage>{props.currPage}</CurrPage>
In the designs, I think this might be a number input where the user can enter in a number to change the page

2024-03-05 08:22 UTC, petabite commented on frontend/src/components/ReferralTableRow.tsx
> +      />
In the video, I see that long names overflow past the dropdown. I'll follow up with them on Slack about what we should do about that.

2024-03-05 08:22 UTC, petabite commented on frontend/src/components/ReferralTableRow.tsx
> +    </RTR_Wrapper>
🔥 💯 Work smarter not harder moment. I like it

2024-03-05 08:22 UTC, petabite commented on frontend/src/components/ReferralTable.tsx
> +  background: var(--Primary, #b64201);
Just for next time, we don't have variables for these set in our CSS, so you can just use the hex code for the color

i.e.
```css
background: #b64201;
```

2024-03-05 22:06 UTC, petabite commented on frontend/src/components/ReferralTable.tsx
> +        <ReferralTableTitle>Referrals:</ReferralTableTitle>
try this:
```css
font-family: "Neutraface Text", sans-serif;
```

2024-03-05 22:47 UTC, petabite commented on backend/src/routes/units.ts
> +router.get("/:id/referrals", requireHousingLocator, UnitController.getUnitReferralsHandler);
Also, RSs should also be able to see the Referrals table in addition to HLs so I don't think we should restrict this to just HLs.

2024-03-06 23:22 UTC, PoliteUnicorn commented on frontend/src/components/ReferralTable.tsx
> +        <ReferralTableTitle>Referrals:</ReferralTableTitle>
I think `font-family: "Neutraface Text";` also works!

2024-03-06 23:22 UTC, PoliteUnicorn commented on frontend/src/components/ReferralTable.tsx
> +  font-family: "Neutra Text";
I think here too! You could replace it with `font-family: "Neutraface Text"`

2024-04-01 00:27 UTC, petabite approved these changes
🚢 🔥

2024-04-01 00:27 UTC, merged