Karen/unit details housing locator
TritonSE/USHS-Housing-Portal pull request #59
Opened 2024-03-07 02:33 UTC by PoliteUnicorn

## Tracking Info

Resolves #52

## Changes
I fixed the spacing and font issues in the UnitDetails page, and I added the navigation bar at the top of the unit details page. 
I also created an edit button and added the landlord information. The view depends on whether the user is a housing locator or not. The edit button also sets the isEditing variable but the form view hasn't been implemented yet.

## Testing
I tested this out on the dummy units created in the database, and switched my role as housing locator to true/false to test that the page views did change. I also used some console.log() statements to test that the edit button was changing the variable correctly.

## Confirmation of Change
**Housing Locator view:** 
<img width="1379" alt="Screenshot 2024-03-06 at 6 26 38 PM" src="https://github.com/TritonSE/USHS-Housing-Portal/assets/35088854/d4f89e40-060b-40fd-825c-081a00ecb799">
**Normal View**
<img width="1392" alt="Screenshot 2024-03-06 at 6 28 50 PM" src="https://github.com/TritonSE/USHS-Housing-Portal/assets/35088854/fe064b1a-a948-472c-a821-4abb68a1f560">

Questions I have:
When displaying the phone number of the landlord, how should it be formatted? Should I add parentheses and dashes into the number or will it have them already?

2024-03-08 21:43 UTC, petabite requested changes
Nice work! Just one small thing: Can we remove the bullet points for the phone number / email of the landlord. See [designs](https://www.figma.com/file/06vEDN5gtlHlC5hxNXMb4g/USHS-Designs?node-id=286%3A16755&mode=dev).

2024-03-08 21:45 UTC, petabite commented
> When displaying the phone number of the landlord, how should it be formatted? Should I add parentheses and dashes into the number or will it have them already?

Let's just leave it as it is for now. We can change the format in the backend if the client wants to see a formatted phone number.

2024-03-10 17:36 UTC, PoliteUnicorn reviewed
I fixed some spacing issues and the landlord information! I think it should be good now but please let me know if anything else needs to be changed!

2024-03-10 19:20 UTC, petabite requested changes
Thanks for fixing the landlord information! I noticed there is a lot of duplicated code. Do you think you can refactor it so that it has all the common elements between the HL and RS view but display just the landlord information for HLs. i.e. instead of having the `if (dataContext.currentUser?.isHousingLocator)`  statement wrap around the entire page, we can just have the statement wrap around just the landlord information (which is the only thing different between the views). We want to eliminate duplicate code as much as possible because if we end up having to change something in one view, we only need to update it in one place instead of two pages, which is good for code maintainability.

2024-03-10 19:20 UTC, petabite commented on frontend/src/pages/UnitDetails.tsx
> +  if (!dataContext.currentUser?.isHousingLocator) {
Is this an intended change?

2024-03-10 22:27 UTC, nbpillai reviewed
the page looks good! but, in general I think it would be cleaner/more consistent to use flex and flex gap to structure everything on the page rather than using margins to add space in some places. (margins can cause problems sometimes when styling other nearby elements)

2024-03-10 23:54 UTC, PoliteUnicorn commented on frontend/src/pages/UnitDetails.tsx
> +  if (!dataContext.currentUser?.isHousingLocator) {
No I undid it!

2024-03-10 23:55 UTC, PoliteUnicorn reviewed
Cleaned up redundant code and used more gap properties instead of margins.

2024-03-12 07:19 UTC, petabite commented on backend/src/routes/units.ts
> +
Oops, this change looks like it's for your new task. Can we revert it and make the changes on a new branch?

2024-03-26 03:06 UTC, petabite approved these changes

2024-03-26 03:07 UTC, merged