Images/Videos, Photo Carousel, Form Attribute
TritonSE/USHS-Housing-Portal pull request #89
Opened 2024-04-22 00:41 UTC by Azhou2023

(Sorry for the large PR)

## Tracking Info

Resolves #79  
Resolves #86 

## Changes

Integrated Firebase Storage to allow for uploading images and videos. Added thumbnails to the unit cards, added a photo carousel in UnitDetails, and added a section to the landlord form to allow for photo/video uploading.

## Testing

Thoroughly tested connection with Firebase, made sure that everything uploaded in correct partitions, made sure that deleting a unit would delete its bucket in Firebase. Ensured photo carousel functionality was correct and all photos/videos appeared where they shoud.

## Confirmation of Change

![Screenshot_1](https://github.com/TritonSE/USHS-Housing-Portal/assets/57163201/55198bfd-2d4f-499b-91ef-51815c89feda)
![Screenshot_2](https://github.com/TritonSE/USHS-Housing-Portal/assets/57163201/0021d109-c973-4e8b-aaae-c9fec343e14d)
![Screenshot_3](https://github.com/TritonSE/USHS-Housing-Portal/assets/57163201/f0e6860b-c8a6-43ff-8841-661284a84258)

2024-04-24 06:10 UTC, petabite requested changes
This is awesome! :fire: Functionality works great! Found a couple stray `console.log`s and a refactoring opportunity.

2024-04-24 06:10 UTC, petabite commented on frontend/src/components/UnitCard.tsx
> +    console.log("hey");
```suggestion
```

2024-04-24 06:10 UTC, petabite commented on frontend/src/pages/UnitDetails.tsx
> +        console.log(urls);
```suggestion
```

2024-04-24 06:10 UTC, petabite commented on frontend/src/pages/UnitDetails.tsx
> +        console.log(urls);
```suggestion
```

2024-04-24 06:10 UTC, petabite commented on frontend/src/pages/UnitDetails.tsx
> +    listAll(ref(storage, `${id}/images/`))
I noticed that the code for getting images/videos is duplicated in a few places. What are your thoughts on extracting that functionality out as a separate service (e.g. in `src/api/images.ts` or something)?

2024-04-24 16:13 UTC, PoliteUnicorn requested changes
Wow! This was super cool and the carousel rotation was really smooth. I was just playing around with it but I noticed that it looks a little different if you change the screen size (some of the image gets cropped). I don't know if changing this is necessary, but it looks great overall!

2024-04-24 16:13 UTC, PoliteUnicorn commented on frontend/public/Trash_Icon.svg
I also included the same trash icon under the name trash-can, so when it's merged we should probably use the same one!

2024-04-24 16:13 UTC, PoliteUnicorn commented on frontend/public/right-arrow.svg
I don't know how feasible this is, but if you want to make the icon a bit darker or lighter, you can use the `filter` property and it can increase the contrast or change the color of an image! (i.e. filter: contrast(200%); or filter: hue-rotate(90deg);)

2024-04-24 16:13 UTC, PoliteUnicorn commented on frontend/src/components/ListingForm/Thumbnail.tsx
This looks good! I was just wondering if there was an alt for each image uploaded?

2024-04-26 00:58 UTC, Azhou2023 commented on frontend/public/right-arrow.svg
Ooh thanks for the suggestion! I'll try that once the new arrow designs come in.

2024-04-26 23:13 UTC, petabite requested changes
Nice! Unit creation with image uploads works perfectly.

Although, I was able to upload a pdf. Adding the `accept` prop to the file inputs to constrain allowed file types to just videos/photos should do the job.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#unique_file_type_specifiers

2024-04-26 23:22 UTC, Azhou2023 commented
> Nice! Unit creation with image uploads works perfectly.
> 
> Although, I was able to upload a pdf. Adding the `accept` prop to the file inputs to constrain allowed file types to just videos/photos should do the job.
> 
> https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#unique_file_type_specifiers

2024-04-26 23:32 UTC, petabite requested changes

2024-04-26 23:32 UTC, petabite commented on frontend/src/components/ListingForm/ImagesVideos.tsx
> +          <input value={""} type="file" id="formId" onChange={handleFormChange} multiple hidden />
This one too?

2024-04-26 23:37 UTC, Azhou2023 commented on frontend/src/components/ListingForm/ImagesVideos.tsx
> +          <input value={""} type="file" id="formId" onChange={handleFormChange} multiple hidden />
🤦‍♂️ idk how I forgot to change both

2024-04-27 01:03 UTC, petabite commented on frontend/src/components/ListingForm/ImagesVideos.tsx
> +          <input value={""} type="file" id="formId" onChange={handleFormChange} multiple hidden />
Loll all good

2024-04-27 01:04 UTC, petabite approved these changes
Nice work! 🔥 🔥

2024-04-30 16:38 UTC, PoliteUnicorn approved these changes
I think it looks good!

2024-04-30 16:41 UTC, merged