Sending email functionality
TritonSE/USHS-Housing-Portal pull request #97
Opened 2024-05-07 09:20 UTC by YashRavipati1

## Tracking Info

Resolves #69 

## Changes

Implemented functionality for automated emails (backend and frontend API service)

## Testing

Created a custom button to send a pre-set automated email to a certain email address every time it was pressed.

## Confirmation of Change

<img width="925" alt="Screenshot 2024-05-07 at 2 19 47 AM" src="https://github.com/TritonSE/USHS-Housing-Portal/assets/63521936/0e8ca6af-8dbb-45ca-bf02-152178679c02">

2024-05-09 21:06 UTC, petabite reviewed
Do we need a route to send emails? Since all the events that trigger an email are processed in the backend, I was thinking we can just call the backend email service's `sendEmail` function wherever we need to send emails. That way we can save a round trip from the frontend to backend. Thoughts?

2024-05-23 06:08 UTC, petabite requested changes
Looking great so far! Just a couple things:

2024-05-23 06:08 UTC, petabite commented on frontend/package-lock.json
Can we delete this file? Looks like you maybe accidentally ran `npm install`

2024-05-23 06:08 UTC, petabite commented on backend/src/services/email.ts
> +    from: "dummyushsacc@gmail.com", // sender address
Is this the same as `process.env.GMAILUSER`?

2024-05-23 06:08 UTC, petabite commented on backend/src/services/referral.ts
> +    status === "leased" &&
```suggestion
    status === "Leased" &&
```
Should this be `"Leased"` if we are expecting all statuses to start with a capital letter?

2024-05-23 06:08 UTC, petabite commented on backend/src/services/referral.ts
> +  }
> - When referral status(es) for unit is set to leased → notify all HLs associated with the ACTIVE referrals for the unit
>     - inactive referral statuses = [ “Denied”, “Canceled” ]

Oops maybe I wasn't too clear about this. When a referral gets set to "Leased", the unit for that referral is leased, so we want to notify all _other_ referrals for that unit that the unit is not available anymore. This currently looks like it just notifies the HL for the current referral.

2024-05-29 20:03 UTC, petabite approved these changes
💯 🔥

2024-05-29 21:12 UTC, Azhou2023 approved these changes
LGTM!

2024-05-29 21:24 UTC, merged